# Generated by Django 2.2.8 on 2020-01-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imag', '0003_auto_20200122_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='subexp',
            field=models.CharField(choices=[(0, 'None'), (1, 'Sample Preparation'), (2, 'Imagery/Spectroscopy'), (3, 'Maintenance'), (4, 'Topography'), (5, 'Atom-Manipulation'), (6, 'Spectrocopy'), (7, 'Sample Growth'), (8, 'Sample/Tip preparation'), (9, 'Ion Deposition')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='subexp',
            field=models.CharField(choices=[(0, 'None'), (1, 'Sample Preparation'), (2, 'Imagery/Spectroscopy'), (3, 'Maintenance'), (4, 'Topography'), (5, 'Atom-Manipulation'), (6, 'Spectrocopy'), (7, 'Sample Growth'), (8, 'Sample/Tip preparation'), (9, 'Ion Deposition')], default=0, max_length=200),
        ),
    ]
