# Generated by Django 2.2.8 on 2020-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imag', '0006_auto_20200122_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='subexp',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Sample Preparation'), (2, 'Imagery/Spectroscopy'), (3, 'Maintenance'), (4, 'Topography'), (5, 'Atom-Manipulation'), (6, 'Spectrocopy'), (7, 'Sample Growth'), (8, 'Sample/Tip preparation'), (9, 'Ion Deposition')], default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='subexp',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Sample Preparation'), (2, 'Imagery/Spectroscopy'), (3, 'Maintenance'), (4, 'Topography'), (5, 'Atom-Manipulation'), (6, 'Spectrocopy'), (7, 'Sample Growth'), (8, 'Sample/Tip preparation'), (9, 'Ion Deposition')], default=0),
        ),
    ]
