# Generated by Django 2.2.8 on 2020-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0002_auto_20200214_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='time_from',
            field=models.SmallIntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='time_to',
            field=models.SmallIntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_from',
            field=models.SmallIntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening'), (3, 'Night')], default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_to',
            field=models.SmallIntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening'), (3, 'Night')], default=0),
        ),
    ]
