# Generated by Django 2.2.8 on 2020-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='exp_type',
            field=models.CharField(choices=[('UHVI', 'UHV Imagery'), ('DUFG', 'Growth DUF'), ('LT4', 'LT-UHV 4 tips'), ('NEARF', 'Near-field microscopy')], default='UHVI', max_length=200),
        ),
    ]
