# Generated by Django 2.2.8 on 2020-01-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imag', '0004_auto_20200122_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='subexp',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subexp',
        ),
    ]
