# Generated by Django 2.2.8 on 2020-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='sample_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='sample_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
