# Generated by Django 2.2.8 on 2020-04-21 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('implant', '0003_auto_20200421_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date_to',
        ),
        migrations.AddField(
            model_name='historicalrecord',
            name='time_from',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalrecord',
            name='time_to',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='time_from',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='time_to',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
