# Generated by Django 2.2.8 on 2020-04-21 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('implant', '0004_auto_20200421_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
