# Generated by Django 2.2.8 on 2020-04-22 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implant', '0005_auto_20200421_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='time_from',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='time_to',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_from',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_to',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
