# Generated by Django 2.2.8 on 2020-02-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='exp_type',
            field=models.CharField(choices=[('PREPC', 'Conventionnal Preparation'), ('FIBp', 'FIB preparation')], default='PREPC', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='billing',
            field=models.CharField(choices=[('SPECTRO', 'Optical Spectroscopy'), ('TEM', 'Electronic Microscopy'), ('PREPA', 'Sample Preparation'), ('MEBA', 'Advanced MEB'), ('FIBCR', 'FIB Clean Room'), ('SOFT', 'Soft Matter'), ('MATCARAC', 'PS2I'), ('MAGNETIC', 'Magnetic Measurement'), ('CHEM', 'Chemistry'), ('CLEANR', 'Clean Room Processes'), ('UHVI', 'UHV Imagery'), ('LT4', 'LT-UHV 4 tips'), ('DUFG', 'Growth DUF'), ('NEARF', 'Near-field microscopy'), ('GROWTHIMP', 'Growth and Implantation'), ('MECA', 'Mechanic Service'), ('ELEC', 'Electronic Service')], default='SPECTRO', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='billing',
            field=models.CharField(choices=[('SPECTRO', 'Optical Spectroscopy'), ('TEM', 'Electronic Microscopy'), ('PREPA', 'Sample Preparation'), ('MEBA', 'Advanced MEB'), ('FIBCR', 'FIB Clean Room'), ('SOFT', 'Soft Matter'), ('MATCARAC', 'PS2I'), ('MAGNETIC', 'Magnetic Measurement'), ('CHEM', 'Chemistry'), ('CLEANR', 'Clean Room Processes'), ('UHVI', 'UHV Imagery'), ('LT4', 'LT-UHV 4 tips'), ('DUFG', 'Growth DUF'), ('NEARF', 'Near-field microscopy'), ('GROWTHIMP', 'Growth and Implantation'), ('MECA', 'Mechanic Service'), ('ELEC', 'Electronic Service')], default='SPECTRO', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prepa.Experiment'),
        ),
    ]
