# Generated by Django 2.2.8 on 2020-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='exp_type',
            field=models.CharField(choices=[('CLEANR', 'Clean Room Processes'), ('GROWTH', 'Growth'), ('IMPLANT', 'Ionic Implantation')], default='CLEANR', max_length=200),
        ),
    ]
