# Generated by Django 2.2.8 on 2020-01-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('met', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='record',
            name='nights',
        ),
    ]
