# Generated by Django 2.2.8 on 2020-04-21 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('implant', '0002_auto_20200421_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
